# Generated by Django 3.2.8 on 2021-11-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuserprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
